export const DEFAULT_TEAMS = [
  { id: 'alphatauri', name: 'AlphaTauri', color: '#00293B', accentColor: '#4E7C9B', logo: '/teams/alphatauri.png' },
  { id: 'aston-martin', name: 'Aston Martin', color: '#006F62', accentColor: '#00D2BE', logo: '/teams/aston-martin.png' },
  { id: 'williams', name: 'Williams Racing', color: '#00A0DE', accentColor: '#005AFF', logo: '/teams/williams.png' },
  { id: 'alpine', name: 'Alpine', color: '#0090FF', accentColor: '#FF87BC', logo: '/teams/alpine.svg' },
  { id: 'mclaren', name: 'McLaren', color: '#FF8000', accentColor: '#FF9E1B', logo: '/teams/mclaren.svg' },
  { id: 'haas', name: 'Haas', color: '#B6BABD', accentColor: '#E6002B', logo: '/teams/haas.png' },
  { id: 'alfa-romeo', name: 'Alfa Romeo KICK', color: '#900000', accentColor: '#C92D2D', logo: '/teams/alfa-romeo.png' },
  { id: 'mercedes', name: 'Mercedes-AMG Petronas', color: '#00A19B', accentColor: '#6CD3BF', logo: '/teams/mercedes.svg' },
  { id: 'ferrari', name: 'Ferrari', color: '#E80020', accentColor: '#FFF200', logo: '/teams/ferrari.png' },
  { id: 'red-bull', name: 'Red Bull / Red Kangaroo', color: '#1E41FF', accentColor: '#FF0000', logo: '/teams/red-bull.png' }
];

export const DEFAULT_DRIVERS = [
  { id: 'drv-1', name: 'Yurii ZAKHARCHUK', country: 'UA', flag: '🇺🇦', teamId: 'mercedes', isAi: false, avatar: '/portraits/yura.png' },
  { id: 'drv-2', name: 'Fernando ALONSO', country: 'ES', flag: '🇪🇸', teamId: 'aston-martin', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png' },
  { id: 'drv-3', name: 'Logan SARGEANT', country: 'US', flag: '🇺🇸', teamId: 'williams', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LOGSAR01_Logan_Sargeant/logsar01.png' },
  { id: 'drv-4', name: 'Alexander ALBON', country: 'TH', flag: '🇹🇭', teamId: 'williams', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png' },
  { id: 'drv-5', name: 'Pierre GASLY', country: 'FR', flag: '🇫🇷', teamId: 'alpine', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png' },
  { id: 'drv-6', name: 'Mykola YAREMA', country: 'UA', flag: '🇺🇦', teamId: 'red-bull', isAi: false, avatar: '/portraits/kolya.png' },
  { id: 'drv-7', name: 'Lando NORRIS', country: 'GB', flag: '🇬🇧', teamId: 'mclaren', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png' },
  { id: 'drv-8', name: 'Nico HULKENBERG', country: 'DE', flag: '🇩🇪', teamId: 'haas', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png' },
  { id: 'drv-9', name: 'Valtteri BOTTAS', country: 'FI', flag: '🇫🇮', teamId: 'alfa-romeo', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png' },
  { id: 'drv-10', name: 'Lance STROLL', country: 'CA', flag: '🇨🇦', teamId: 'aston-martin', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png' },
  { id: 'drv-11', name: 'Alexsandr GROMOV', country: 'UA', flag: '🇺🇦', teamId: 'mercedes', isAi: false, avatar: '/portraits/sashko.png' },
  { id: 'drv-12', name: 'Kevin MAGNUSSEN', country: 'DK', flag: '🇩🇰', teamId: 'haas', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png' },
  { id: 'drv-13', name: 'Esteban OCON', country: 'FR', flag: '🇫🇷', teamId: 'alpine', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png' },
  { id: 'drv-14', name: 'Carlos SAINZ', country: 'ES', flag: '🇪🇸', teamId: 'ferrari', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png' },
  { id: 'drv-15', name: 'Sergio PÉREZ', country: 'MX', flag: '🇲🇽', teamId: 'alphatauri', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png' },
  { id: 'drv-16', name: 'Charles LECLERC', country: 'MC', flag: '🇲🇨', teamId: 'ferrari', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png' },
  { id: 'drv-17', name: 'Denys KOVALENKO', country: 'UA', flag: '🇺🇦', teamId: 'red-bull', isAi: false, avatar: '/portraits/denya.png' },
  { id: 'drv-18', name: 'Max VERSTAPPEN', country: 'NL', flag: '🇳🇱', teamId: 'alphatauri', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png' },
  { id: 'drv-19', name: 'Oscar PIASTRI', country: 'AU', flag: '🇦🇺', teamId: 'mclaren', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png' },
  { id: 'drv-20', name: 'ZHOU Guanyu', country: 'CN', flag: '🇨🇳', teamId: 'alfa-romeo', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Zhou_Guanyu/guazho01.png' },
  { id: 'drv-21', name: 'Daniel RICCIARDO', country: 'AU', flag: '🇦🇺', teamId: 'alphatauri', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png' },
  { id: 'drv-22', name: 'Yuki TSUNODA', country: 'JP', flag: '🇯🇵', teamId: 'alphatauri', isAi: true, avatar: 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png' }
];

export const DEFAULT_POINTS_MAP = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1];
export const SPRINT_POINTS_MAP = [8, 7, 6, 5, 4, 3, 2, 1];

export const DEFAULT_RACES = [
  {
    id: 'race-1',
    title: 'Bahrain Grand Prix',
    subtitle: 'BAHRAIN INTERNATIONAL CIRCUIT - RACE 1',
    date: '2026-03-02',
    status: 'completed',
    fastestLapDriverId: 'drv-11',
    results: [
      { driverId: 'drv-1', grid: 8, stops: 1, bestLap: '1:34.565', totalTime: '50:18.047', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 3, stops: 1, bestLap: '1:35.044', totalTime: '+1.116', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 4, stops: 1, bestLap: '1:34.852', totalTime: '+1.463', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 20, stops: 1, bestLap: '1:34.295', totalTime: '+2.565', penaltySeconds: 0, penaltyLabel: '⚙️ Телепорт/Глитч', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 16, stops: 1, bestLap: '1:36.142', totalTime: '+4.788', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 5, stops: 1, bestLap: '1:35.434', totalTime: '+6.879', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 17, stops: 1, bestLap: '1:35.909', totalTime: '+7.838', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 9, stops: 1, bestLap: '1:35.807', totalTime: '+8.527', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 18, stops: 1, bestLap: '1:36.060', totalTime: '+9.085', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 1, stops: 2, bestLap: '1:33.942', totalTime: '+10.111', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-6', grid: 2, stops: 3, bestLap: '1:34.220', totalTime: '+5.500', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 14, stops: 1, bestLap: '1:36.044', totalTime: '+10.676', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 19, stops: 1, bestLap: '1:36.445', totalTime: '+11.148', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 15, stops: 1, bestLap: '1:36.218', totalTime: '+11.571', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-15', grid: 10, stops: 1, bestLap: '1:35.943', totalTime: '+12.437', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 11, stops: 1, bestLap: '1:35.699', totalTime: '+13.559', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 7, stops: 1, bestLap: '1:35.403', totalTime: '+14.295', penaltySeconds: 0, penaltyLabel: '⚙️ Техн. Баг', status: 'FINISHED' },
      { driverId: 'drv-18', grid: 13, stops: 1, bestLap: '1:36.280', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-19', grid: 12, stops: 1, bestLap: '1:35.943', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-20', grid: 6, stops: 0, bestLap: '1:36.139', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-2',
    title: 'Saudi Arabian Grand Prix',
    subtitle: 'JEDDAH CORNICHE CIRCUIT - RACE 2',
    date: '2026-03-09',
    status: 'completed',
    fastestLapDriverId: 'drv-1',
    results: [
      { driverId: 'drv-1', grid: 1, stops: 2, bestLap: '1:31.976', totalTime: '50:02.104', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 5, stops: 1, bestLap: '1:33.930', totalTime: '+1.845', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-15', grid: 4, stops: 1, bestLap: '1:34.393', totalTime: '+2.065', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-18', grid: 3, stops: 1, bestLap: '1:34.219', totalTime: '+4.687', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 9, stops: 1, bestLap: '1:34.142', totalTime: '+10.465', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 10, stops: 1, bestLap: '1:33.788', totalTime: '+11.282', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 7, stops: 1, bestLap: '1:34.327', totalTime: '+11.474', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 8, stops: 1, bestLap: '1:34.006', totalTime: '+14.623', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 19, stops: 1, bestLap: '1:35.057', totalTime: '+22.105', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 16, stops: 1, bestLap: '1:34.729', totalTime: '+22.257', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 11, stops: 1, bestLap: '1:34.539', totalTime: '+25.508', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 2, stops: 2, bestLap: '1:33.658', totalTime: '+45.638', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 14, stops: 2, bestLap: '1:35.282', totalTime: '+46.895', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 20, stops: 1, bestLap: '1:34.400', totalTime: '+47.183', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 13, stops: 2, bestLap: '1:34.300', totalTime: '+47.331', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 12, stops: 3, bestLap: '1:33.839', totalTime: '+1:14.937', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 17, stops: 3, bestLap: '1:34.027', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 6, stops: 1, bestLap: '1:34.432', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-12', grid: 15, stops: 1, bestLap: '1:35.092', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-6', grid: 18, stops: 1, bestLap: '1:33.763', totalTime: 'x1 (+3 secs.)', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' }
    ]
  },
  {
    id: 'race-3',
    title: 'Australian Grand Prix',
    subtitle: 'ALBERT PARK CIRCUIT - RACE 3',
    date: '2026-03-16',
    status: 'completed',
    fastestLapDriverId: 'drv-1',
    results: [
      { driverId: 'drv-1', grid: 2, stops: 1, bestLap: '1:21.421', totalTime: '40:49.466', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-6', grid: 1, stops: 1, bestLap: '1:22.703', totalTime: '+10.309', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 5, stops: 1, bestLap: '1:22.530', totalTime: '+25.648', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 6, stops: 1, bestLap: '1:22.721', totalTime: '+27.336', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 9, stops: 1, bestLap: '1:23.194', totalTime: '+28.664', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 8, stops: 1, bestLap: '1:23.750', totalTime: '+40.547', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 4, stops: 1, bestLap: '1:23.681', totalTime: '+44.139', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 10, stops: 1, bestLap: '1:23.877', totalTime: '+45.137', penaltySeconds: 5, penaltyLabel: 'x1 (+5 secs.)', status: 'FINISHED' },
      { driverId: 'drv-15', grid: 11, stops: 1, bestLap: '1:24.105', totalTime: '+47.849', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 12, stops: 1, bestLap: '1:23.963', totalTime: '+49.718', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 13, stops: 1, bestLap: '1:23.444', totalTime: '+50.277', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-18', grid: 16, stops: 1, bestLap: '1:22.961', totalTime: '+50.566', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 17, stops: 1, bestLap: '1:24.138', totalTime: '+51.013', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 18, stops: 1, bestLap: '1:24.197', totalTime: '+51.221', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 19, stops: 1, bestLap: '1:23.926', totalTime: '+51.754', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 14, stops: 1, bestLap: '1:23.965', totalTime: '+52.124', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 3, stops: 2, bestLap: '1:21.743', totalTime: '+1:01.763', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 20, stops: 2, bestLap: '1:22.608', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 15, stops: 1, bestLap: '1:23.913', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-9', grid: 7, stops: 0, bestLap: '1:30.788', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-4',
    title: 'Azerbaijan Grand Prix (Sprint)',
    subtitle: 'BAKU CITY CIRCUIT - SPRINT RACE 4',
    date: '2026-03-23',
    status: 'completed',
    isSprint: true,
    isCancelled: false,
    hasPressRelease: true,
    fastestLapDriverId: '',
    results: [
      { driverId: 'drv-18', grid: 1, stops: 0, bestLap: '1:42.100', totalTime: '24:15.102', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 2, stops: 0, bestLap: '1:42.500', totalTime: '+1.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 3, stops: 0, bestLap: '1:42.800', totalTime: '+3.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-15', grid: 4, stops: 0, bestLap: '1:42.600', totalTime: '+4.500', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 5, stops: 0, bestLap: '1:43.000', totalTime: '+6.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 6, stops: 0, bestLap: '1:43.100', totalTime: '+7.800', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 7, stops: 0, bestLap: '1:43.300', totalTime: '+9.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 8, stops: 0, bestLap: '1:43.400', totalTime: '+10.500', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 9, stops: 0, bestLap: '1:43.500', totalTime: '+11.800', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 10, stops: 0, bestLap: '1:43.700', totalTime: '+12.400', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 11, stops: 0, bestLap: '1:43.800', totalTime: '+13.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 12, stops: 0, bestLap: '1:43.900', totalTime: '+14.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 13, stops: 0, bestLap: '1:44.000', totalTime: '+15.000', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 14, stops: 0, bestLap: '1:44.200', totalTime: '+16.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 15, stops: 0, bestLap: '1:44.300', totalTime: '+17.300', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 16, stops: 0, bestLap: '1:44.500', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-17', grid: 17, stops: 0, bestLap: '1:44.700', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-12', grid: 18, stops: 0, bestLap: '1:44.900', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-1', grid: 19, stops: 0, bestLap: '1:45.100', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-6', grid: 20, stops: 0, bestLap: '1:45.500', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-5',
    title: 'Miami Grand Prix',
    subtitle: 'MIAMI INTERNATIONAL AUTODROME - RACE 5',
    date: '2026-05-03',
    status: 'completed',
    fastestLapDriverId: 'drv-1',
    hasPenaltyAnnouncement: true,
    penaltyData: {
      offenderName: 'Carlos SAINZ',
      offenderCar: 'Car #55 • Ferrari',
      victimName: 'Alexsandr GROMOV (PABV)',
      victimCar: 'Car #63 • Mercedes-AMG Petronas',
      penaltyText: '+10 SEC TIME PENALTY',
      penaltyValue: '+10 SECONDS',
      docNo: 'DEC-2026-MIA-55',
      circuitName: 'MIAMI INTERNATIONAL AUTODROME',
      headline: 'ШТРАФ +10 СЕКУНД ДЛЯ CARLOS SAINZ (#55 FERRARI)',
      description: 'Стюарды изучили видеозаписи с онборд-камер, данные GPS и телеметрии. Было установлено, что болид #55 (Carlos Sainz) совершил агрессивный и нескоординированный маневр обгона, вызвав фатальный контакт с болидом #63 (Alexsandr GROMOV / PABV).',
      consequences: '💥 Последствия инцидента: Болид Сашка получил несовместимые с продолжением гонки повреждения (Terminal Damage) и сошел с дистанции.',
      outcome: '⚖️ ИТОГОВЫЙ ШТРАФ: +10 секунд к финальному времени гонки. Карлос Сайнс перемещается с 6-го места на 17-е место.'
    },
    results: [
      { driverId: 'drv-6', grid: 1, stops: 1, bestLap: '1:32.323', totalTime: '48:03.537', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-18', grid: 4, stops: 1, bestLap: '1:33.366', totalTime: '+2.141', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-15', grid: 5, stops: 1, bestLap: '1:33.491', totalTime: '+2.189', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 2, stops: 2, bestLap: '1:32.243', totalTime: '+2.515', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 10, stops: 1, bestLap: '1:33.456', totalTime: '+2.515', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 6, stops: 1, bestLap: '1:34.120', totalTime: '+5.615', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 12, stops: 1, bestLap: '1:33.820', totalTime: '+6.059', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 9, stops: 1, bestLap: '1:34.740', totalTime: '+7.017', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 14, stops: 1, bestLap: '1:34.039', totalTime: '+7.386', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 16, stops: 1, bestLap: '1:33.737', totalTime: '+8.169', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 11, stops: 1, bestLap: '1:34.259', totalTime: '+8.702', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 18, stops: 1, bestLap: '1:33.968', totalTime: '+10.165', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 13, stops: 1, bestLap: '1:34.058', totalTime: '+11.249', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 15, stops: 1, bestLap: '1:34.337', totalTime: '+11.994', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 17, stops: 1, bestLap: '1:33.920', totalTime: '+12.394', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 7, stops: 1, bestLap: '1:34.285', totalTime: '+13.941', penaltySeconds: 10, penaltyLabel: '⚠️ +10 sec (Убийство Сашка)', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 20, stops: 1, bestLap: '1:33.802', totalTime: '+15.926', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 8, stops: 1, bestLap: '1:34.119', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 19, stops: 1, bestLap: '1:33.994', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-11', grid: 3, stops: 1, bestLap: '1:32.956', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '💥 Terminal Damage (Crash w/ Sainz)', status: 'DNF' }
    ]
  },
  {
    id: 'race-6',
    title: 'Emilia Romagna Grand Prix',
    subtitle: 'AUTODROMO ENZO E DINO FERRARI (IMOLA) - RACE 6',
    date: '2026-05-17',
    status: 'completed',
    fastestLapDriverId: 'drv-6',
    results: [
      { driverId: 'drv-6', grid: 1, stops: 2, bestLap: '1:17.915', totalTime: '47:48.650', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 3, stops: 4, bestLap: '1:20.283', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 18, stops: 1, bestLap: '1:24.252', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 9, stops: 1, bestLap: '1:24.436', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 20, stops: 1, bestLap: '1:24.862', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 12, stops: 1, bestLap: '1:24.733', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 10, stops: 1, bestLap: '1:24.257', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 8, stops: 1, bestLap: '1:24.385', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 6, stops: 1, bestLap: '1:24.371', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 7, stops: 1, bestLap: '1:24.416', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 13, stops: 1, bestLap: '1:24.550', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 11, stops: 1, bestLap: '1:24.654', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 15, stops: 1, bestLap: '1:24.558', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 19, stops: 1, bestLap: '1:24.926', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 5, stops: 1, bestLap: '1:23.916', totalTime: '+2 Laps', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 14, stops: 1, bestLap: '1:24.665', totalTime: '+2 Laps', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 4, stops: 1, bestLap: '1:22.471', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-9', grid: 17, stops: 1, bestLap: '1:24.905', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-11', grid: 2, stops: 1, bestLap: '1:19.208', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-8', grid: 16, stops: 0, bestLap: '1:24.970', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-7',
    title: 'Monaco Grand Prix',
    subtitle: 'CIRCUIT DE MONACO - RACE 7',
    date: '2026-05-24',
    status: 'completed',
    fastestLapDriverId: 'drv-6',
    results: [
      { driverId: 'drv-6', grid: 2, stops: 2, bestLap: '1:13.881', totalTime: '46:58.120', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 3, stops: 1, bestLap: '1:15.956', totalTime: '+40.717', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 7, stops: 1, bestLap: '1:15.984', totalTime: '+1:01.212', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 5, stops: 1, bestLap: '1:16.182', totalTime: '+1:08.336', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 10, stops: 1, bestLap: '1:15.890', totalTime: '+1:09.061', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 8, stops: 1, bestLap: '1:15.057', totalTime: '+1:10.500', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 9, stops: 1, bestLap: '1:16.177', totalTime: '+1:11.714', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 6, stops: 1, bestLap: '1:16.122', totalTime: '+1:13.167', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 11, stops: 1, bestLap: '1:16.433', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 14, stops: 1, bestLap: '1:16.060', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 12, stops: 1, bestLap: '1:16.890', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 19, stops: 1, bestLap: '1:16.892', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 17, stops: 1, bestLap: '1:16.900', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 18, stops: 1, bestLap: '1:16.424', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 1, stops: 2, bestLap: '1:14.145', totalTime: '+1 Lap', penaltySeconds: 3, penaltyLabel: 'x1 (+3 secs.)', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 20, stops: 1, bestLap: '1:16.413', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 15, stops: 1, bestLap: '1:16.456', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 4, stops: 1, bestLap: '1:16.036', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-20', grid: 13, stops: 1, bestLap: '1:16.280', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' },
      { driverId: 'drv-17', grid: 16, stops: 1, bestLap: '1:16.939', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-8',
    title: 'Spanish Grand Prix',
    subtitle: 'CIRCUIT DE BARCELONA-CATALUNYA - RACE 8',
    date: '2026-05-31',
    status: 'completed',
    fastestLapDriverId: 'drv-6',
    hasPenaltyAnnouncement: true,
    penaltyData: {
      offenderName: 'Yuki TSUNODA',
      offenderCar: 'Car #22 • AlphaTauri',
      victimName: 'Yurii ZAKHARCHUK (imnot4777)',
      victimCar: 'Car #44 • Mercedes-AMG Petronas',
      penaltyText: '+20 SEC TIME PENALTY',
      penaltyValue: '+20 SECONDS',
      docNo: 'DEC-2026-ESP-22',
      circuitName: 'CIRCUIT DE BARCELONA-CATALUNYA',
      headline: 'ШТРАФ +20 СЕКУНД ДЛЯ YUKI TSUNODA (#22 ALPHATAURI)',
      description: 'Стюарды изучили записи онборд-камер и телеметрии. Было установлено, что болид #22 (Yuki Tsunoda) совершил агрессивный маневр атаки, развернув болид #44 (Yurii ZAKHARCHUK / imnot4777) в защитный барьер.',
      consequences: '💥 Последствия инцидента: Юрий Захарчук был отброшен в стену и потерял позиции, а сам Юки Цунода сломал подвеску/колесо своей машины и сошёл с дистанции (DNF).',
      outcome: '⚖️ ИТОГОВЫЙ ШТРАФ: +20 секунд к итоговому результату за опасное вождение и разворот соперника.'
    },
    results: [
      { driverId: 'drv-6', grid: 1, stops: 2, bestLap: '1:14.360', totalTime: '44:54.808', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 2, stops: 1, bestLap: '1:15.702', totalTime: '+10.063', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 8, stops: 1, bestLap: '1:17.167', totalTime: '+20.827', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 6, stops: 1, bestLap: '1:17.156', totalTime: '+21.402', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 9, stops: 1, bestLap: '1:18.063', totalTime: '+23.528', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 10, stops: 1, bestLap: '1:16.847', totalTime: '+24.005', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 17, stops: 1, bestLap: '1:17.409', totalTime: '+24.419', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 7, stops: 1, bestLap: '1:17.953', totalTime: '+25.260', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 14, stops: 1, bestLap: '1:18.068', totalTime: '+25.998', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 5, stops: 1, bestLap: '1:17.975', totalTime: '+31.253', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 13, stops: 1, bestLap: '1:17.944', totalTime: '+31.818', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 15, stops: 1, bestLap: '1:17.164', totalTime: '+32.881', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 12, stops: 1, bestLap: '1:17.682', totalTime: '+34.192', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 18, stops: 1, bestLap: '1:17.601', totalTime: '+34.504', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 20, stops: 1, bestLap: '1:17.416', totalTime: '+35.267', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 19, stops: 1, bestLap: '1:18.050', totalTime: '+35.617', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 3, stops: 2, bestLap: '1:16.322', totalTime: '+36.835', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 11, stops: 2, bestLap: '1:16.812', totalTime: '+42.675', penaltySeconds: 0, penaltyLabel: '💥 Развёрнут Tsunoda в стену', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 4, stops: 1, bestLap: '1:17.379', totalTime: 'DNF', penaltySeconds: 20, penaltyLabel: '⚠️ +20 sec (Выбил Юру в стену)', status: 'DNF' },
      { driverId: 'drv-10', grid: 16, stops: 0, bestLap: '1:19.139', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-9',
    title: 'Canadian Grand Prix',
    subtitle: 'CIRCUIT GILLES VILLENEUVE (MONTREAL) - RACE 9',
    date: '2026-06-07',
    status: 'completed',
    fastestLapDriverId: 'drv-6',
    results: [
      { driverId: 'drv-6', grid: 1, stops: 2, bestLap: '1:13.545', totalTime: '44:54.901', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-11', grid: 2, stops: 1, bestLap: '1:14.605', totalTime: '+0.269', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 3, stops: 1, bestLap: '1:14.280', totalTime: '+3.867', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 4, stops: 1, bestLap: '1:14.610', totalTime: '+5.241', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 6, stops: 1, bestLap: '1:15.040', totalTime: '+9.006', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 5, stops: 1, bestLap: '1:15.214', totalTime: '+12.582', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 12, stops: 1, bestLap: '1:15.398', totalTime: '+20.731', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 7, stops: 1, bestLap: '1:15.503', totalTime: '+21.793', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 9, stops: 1, bestLap: '1:15.026', totalTime: '+22.421', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 14, stops: 1, bestLap: '1:15.111', totalTime: '+23.679', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 10, stops: 1, bestLap: '1:15.253', totalTime: '+25.720', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 18, stops: 1, bestLap: '1:15.446', totalTime: '+29.929', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 8, stops: 2, bestLap: '1:14.789', totalTime: '+30.934', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 13, stops: 1, bestLap: '1:15.343', totalTime: '+31.859', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 16, stops: 1, bestLap: '1:15.669', totalTime: '+33.085', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 15, stops: 1, bestLap: '1:15.598', totalTime: '+33.156', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 11, stops: 1, bestLap: '1:15.204', totalTime: '+44.801', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 20, stops: 1, bestLap: '1:15.204', totalTime: '+56.813', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 19, stops: 3, bestLap: '1:14.889', totalTime: '+2 Laps', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 17, stops: 0, bestLap: '1:16.680', totalTime: 'DNF', penaltySeconds: 0, penaltyLabel: '', status: 'DNF' }
    ]
  },
  {
    id: 'race-10-sprint',
    title: 'Austrian Grand Prix (Sprint)',
    subtitle: 'RED BULL RING (SPIELBERG) - SPRINT RACE 10',
    date: '2026-06-27',
    status: 'completed',
    isSprint: true,
    fastestLapDriverId: '',
    results: [
      { driverId: 'drv-11', grid: 2, stops: 0, bestLap: '1:07.563', totalTime: '13:43.938', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 3, stops: 0, bestLap: '1:07.887', totalTime: '+17.150', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 4, stops: 0, bestLap: '1:09.430', totalTime: '+20.840', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 9, stops: 0, bestLap: '1:09.399', totalTime: '+21.658', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 8, stops: 0, bestLap: '1:09.249', totalTime: '+22.196', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 7, stops: 0, bestLap: '1:09.322', totalTime: '+23.298', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 10, stops: 0, bestLap: '1:09.401', totalTime: '+23.827', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 12, stops: 0, bestLap: '1:09.657', totalTime: '+25.960', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 6, stops: 0, bestLap: '1:09.550', totalTime: '+26.409', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 14, stops: 0, bestLap: '1:09.249', totalTime: '+26.836', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 15, stops: 0, bestLap: '1:09.263', totalTime: '+27.209', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 16, stops: 0, bestLap: '1:09.613', totalTime: '+27.502', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 11, stops: 0, bestLap: '1:09.388', totalTime: '+27.867', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 13, stops: 0, bestLap: '1:09.668', totalTime: '+28.623', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 17, stops: 0, bestLap: '1:09.770', totalTime: '+29.806', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 19, stops: 0, bestLap: '1:09.986', totalTime: '+34.173', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 18, stops: 0, bestLap: '1:09.962', totalTime: '+34.458', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 5, stops: 1, bestLap: '1:08.524', totalTime: '+46.157', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 1, stops: 1, bestLap: '1:08.626', totalTime: '+50.158', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-6', grid: 20, stops: 0, bestLap: '1:07.845', totalTime: '+1:12.000', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' }
    ]
  },
  {
    id: 'race-10',
    title: 'Austrian Grand Prix',
    subtitle: 'RED BULL RING (SPIELBERG) - RACE 10',
    date: '2026-06-28',
    status: 'completed',
    fastestLapDriverId: 'drv-6',
    results: [
      { driverId: 'drv-11', grid: 1, stops: 1, bestLap: '1:07.240', totalTime: '42:18.520', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-17', grid: 2, stops: 1, bestLap: '1:07.610', totalTime: '+2.140', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-4', grid: 4, stops: 1, bestLap: '1:08.390', totalTime: '+8.450', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-22', grid: 3, stops: 1, bestLap: '1:08.430', totalTime: '+11.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-1', grid: 19, stops: 1, bestLap: '1:07.820', totalTime: '+14.650', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-6', grid: 20, stops: 2, bestLap: '1:06.940', totalTime: '+18.910', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-13', grid: 7, stops: 1, bestLap: '1:08.920', totalTime: '+24.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-9', grid: 13, stops: 1, bestLap: '1:08.890', totalTime: '+27.450', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-8', grid: 10, stops: 1, bestLap: '1:08.950', totalTime: '+30.120', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-5', grid: 6, stops: 1, bestLap: '1:08.870', totalTime: '+32.840', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-16', grid: 5, stops: 1, bestLap: '1:08.990', totalTime: '+34.500', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-7', grid: 8, stops: 1, bestLap: '1:09.120', totalTime: '+36.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-12', grid: 15, stops: 1, bestLap: '1:09.340', totalTime: '+40.100', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-2', grid: 18, stops: 1, bestLap: '1:09.150', totalTime: '+42.600', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-21', grid: 11, stops: 1, bestLap: '1:09.400', totalTime: '+45.800', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-3', grid: 17, stops: 1, bestLap: '1:09.550', totalTime: '+48.200', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-19', grid: 12, stops: 1, bestLap: '1:09.600', totalTime: '+51.300', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-20', grid: 9, stops: 2, bestLap: '1:09.220', totalTime: '+55.700', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-14', grid: 14, stops: 1, bestLap: '1:09.650', totalTime: '+58.400', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' },
      { driverId: 'drv-10', grid: 16, stops: 2, bestLap: '1:09.800', totalTime: '+1 Lap', penaltySeconds: 0, penaltyLabel: '', status: 'FINISHED' }
    ]
  }
];

export const DEFAULT_PENALTIES = [
  { id: 'pen-2', driverId: 'drv-17', raceId: 'race-1', type: 'TIME', value: 3, reason: 'Track limits / penalty (x1)', date: '2026-03-02' },
  { id: 'pen-3', driverId: 'drv-1', raceId: 'race-2', type: 'TIME', value: 3, reason: 'Track limits warning (x1)', date: '2026-03-09' },
  { id: 'pen-4', driverId: 'drv-6', raceId: 'race-2', type: 'TIME', value: 3, reason: 'Track limits warning (x1)', date: '2026-03-09' },
  { id: 'pen-5', driverId: 'drv-16', raceId: 'race-3', type: 'TIME', value: 5, reason: 'Track limits warning x1 (+5 secs.)', date: '2026-03-16' },
  { id: 'pen-6', driverId: 'drv-14', raceId: 'race-5', type: 'TIME', value: 10, reason: 'Штраф +10 сек за столкновение и уничтожение болида Alexsandr GROMOV (Terminal Damage)', date: '2026-05-03' },
  { id: 'pen-7', driverId: 'drv-22', raceId: 'race-8', type: 'TIME', value: 20, reason: 'Штраф +20 сек за столкновение, разворот Юрия Захарчука в стену и повреждение своего колеса (DNF)', date: '2026-05-31' }
];

export const BREAKING_TRANSFERS = [
  {
    id: 'tr-1',
    driverName: 'Олександр Громов (PABV)',
    type: 'EXTENDED',
    title: 'Олександр Громов залишається в AL-Mercedes',
    subtitle: 'Mercedes-AMG Petronas F1 Team продлевает контракт с Александром Громовым',
    image: '/announcements/gromov_mercedes.png',
    fromTeam: 'Mercedes-AMG Petronas',
    toTeam: 'Mercedes-AMG Petronas',
    badgeText: 'REMAINS IN MERCEDES'
  },
  {
    id: 'tr-2',
    driverName: 'Денис Коваленко (ProstoDenya)',
    type: 'TRANSFERRED',
    title: 'Денис Коваленко офіційно переходить из Mercedes в Red Kangaroo',
    subtitle: 'Денис Коваленко переходит в команду Red Bull Racing со всеми набранными очками',
    image: '/announcements/kovalenko_redbull.png',
    fromTeam: 'Mercedes-AMG Petronas',
    toTeam: 'Red Bull Racing',
    badgeText: 'JOINED RED BULL'
  },
  {
    id: 'tr-3',
    driverName: 'Микола Ярема (kolyacoolguy)',
    type: 'TRANSFERRED',
    title: 'Микола Ярема офіційно переходить из AlphaTauri в Red Kangaroo',
    subtitle: 'Лидер Гран-при Майами Микола Ярема переходит из AlphaTauri в Red Bull Racing',
    image: '/announcements/yarema_redbull.png',
    fromTeam: 'AlphaTauri',
    toTeam: 'Red Bull Racing',
    badgeText: 'JOINED RED BULL'
  },
  {
    id: 'tr-4',
    driverName: 'Юрий Захарчук (imnot4777)',
    type: 'TRANSFERRED',
    title: 'Юрий Захарчук официально переходит из AlphaTauri в Mercedes F1 Team',
    subtitle: 'Лидер личного зачёта Юрий Захарчук подписывает контракт с Mercedes-AMG Petronas',
    image: '/announcements/zakharchuk_mercedes.png',
    fromTeam: 'AlphaTauri',
    toTeam: 'Mercedes-AMG Petronas',
    badgeText: 'JOINED MERCEDES'
  }
];
